create table public.listing_reviews (
  review_id bigint generated by default as identity not null,
  listing_id bigint not null,
  fingerprint text not null,
  rating smallint not null,
  review_text text null,
  created_at timestamp with time zone not null default now(),
  constraint listing_reviews_pkey primary key (review_id),
  constraint listing_reviews_listing_id_fkey foreign KEY (listing_id) references "Property_Listing" (listing_id) on delete CASCADE,
  constraint listing_reviews_rating_check check (
    (
      (rating >= 1)
      and (rating <= 5)
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists listing_reviews_one_per_device on public.listing_reviews using btree (listing_id, fingerprint) TABLESPACE pg_default;

create index IF not exists listing_reviews_listing_id_idx on public.listing_reviews using btree (listing_id) TABLESPACE pg_default;